import { Listing } from "@/types/listing";

export const listings: Listing[] = [
  { id: "noida-pg", title: "Single PG near Noida Sector 62 Metro", description: "A bright, secure room close to the metro with a peaceful study-friendly setting.", image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1000&q=85", price: 4500, location: "Sector 62, Noida", state: "Uttar Pradesh", roomType: "Single", preferredTenant: "Boys", availabilityStatus: "Available", phone: "9876543210", owner: "Pratyush", coordinates: { lat: 28.6271, lon: 77.3649 }, reviews: [{ id: "r1", owner: "Aarav", rating: 5, comment: "Very clean room and a convenient location for students." }] },
  { id: "cyber-city", title: "Single PG near Noida Sector 62 Metro", description: "Comfortable student accommodation with everything needed for an easy daily routine.", image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=85", price: 5359, location: "DLF Cyber City, Gurugram", state: "Haryana", roomType: "Double", preferredTenant: "Any", availabilityStatus: "Available", phone: "9876543210", owner: "Ananya", coordinates: { lat: 28.4949, lon: 77.0897 }, reviews: [] },
  { id: "du-north", title: "Budget PG near DU North Campus", description: "A comfortable, low-budget PG ideal for DU students near North Campus.", image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1000&q=85", price: 4867, location: "Kamla Nagar, Delhi", state: "Delhi", roomType: "Shared", preferredTenant: "Boys", availabilityStatus: "Available", phone: "9876543210", owner: "Rohit", coordinates: { lat: 28.681, lon: 77.2043 }, reviews: [] },
  { id: "whitefield", title: "Single Room near Whitefield IT Park", description: "A quiet, fully furnished room close to Whitefield's IT hubs.", image: "https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1000&q=85", price: 3972, location: "Whitefield, Bengaluru", state: "Karnataka", roomType: "Single", preferredTenant: "Any", availabilityStatus: "Available", phone: "9876543210", owner: "Meera", coordinates: { lat: 12.9698, lon: 77.7499 }, reviews: [] }
];
export const getListing = (id: string) => listings.find((listing) => listing.id === id) ?? listings[0];
